#!/bin/bash
# ワークフロー初期化フック
# セッション開始時に、憲法・契約・ワークフロー情報をコンテキストに追加

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

echo "# AI駆動開発 コンテキスト情報"
echo ""

# 1. 憲法（Constitution）を読み込み
echo "## 憲法（Constitution）"
echo ""
echo "以下はこのプロジェクトの不変原則です。すべての実装はこれに従う必要があります。"
echo ""

# index.md を最初に読み込む
if [ -f "$PROJECT_DIR/guardrails/constitution/index.md" ]; then
  echo "### guardrails/constitution/index.md"
  echo ""
  cat "$PROJECT_DIR/guardrails/constitution/index.md"
  echo ""
  echo "---"
  echo ""
fi

# サブディレクトリの md ファイルを読み込む
find "$PROJECT_DIR/guardrails/constitution" -mindepth 2 -name "*.md" -type f | sort | while read -r file; do
  relative_path="${file#$PROJECT_DIR/}"
  echo "### $relative_path"
  echo ""
  cat "$file"
  echo ""
  echo "---"
  echo ""
done

# 2. ビジネス契約のみ読み込み（API YAMLはスキップ）
echo "## ビジネス契約（Business Contracts）"
echo ""
echo "以下は既存のビジネス契約です。"
echo ""

find "$PROJECT_DIR/contracts/business" -name "*.md" -type f | sort | while read -r file; do
  relative_path="${file#$PROJECT_DIR/}"
  echo "### $relative_path"
  echo ""
  cat "$file"
  echo ""
  echo "---"
  echo ""
done

# 3. ワークフロー実行指示
echo "## ワークフロー実行指示"
echo ""
echo "新しい機能実装を開始する場合は、以下のステップで進めてください："
echo ""
echo "### Step 1: Goal登録"
echo ""
echo "ユーザーの発言をそのままGoalとして記録する。"
echo ""
echo "### Step 2: 実装範囲の確認"
echo ""
echo "最初に**AskUserQuestionツール**で以下の4択を提示し、実装範囲を確認する："
echo ""
echo "| 選択肢 | 内容 |"
echo "|--------|------|"
echo "| 契約のみ | ビジネス契約（contracts/business）の定義まで |"
echo "| ポリシーまで | 契約 + ポリシー（policies）まで |"
echo "| フロントエンドまで | 契約 + ポリシー + フロントエンド（Mock）実装まで |"
echo "| 最後まで | バックエンド、E2Eを含む全レイヤーを実装 |"
echo ""
echo "### Step 3: 深掘りインタビュー（対話で要件を引き出す）"
echo ""
echo "**AskUserQuestionツール**を使い、要件がクリアになるまで繰り返し質問する。"
echo ""
echo "#### 終了条件"
echo ""
echo "以下の全てが明確になるまで質問を続ける："
echo ""
echo "- **Actor**: 誰が使うか"
echo "- **Want**: 何をしたいか"
echo "- **Because**: なぜ必要か"
echo "- **Acceptance**: どうなれば成功か"
echo "- **Constraints**: 制約があるか（オプション）"
echo ""
echo "#### 質問の深さ（抽象度と規模に応じて調整）"
echo ""
echo "| ユーザーの発言 | 質問の深さ |"
echo "|---------------|-----------|"
echo "| 抽象的・大規模（例: 「メンバー管理機能がほしい」） | 多くの質問が必要。Actor/Want/Acceptanceを詳細に確認 |"
echo "| 具体的・小規模（例: 「削除ボタンにconfirmを追加」） | 少ない質問で済む。確認程度でOK |"
echo ""
echo "#### 質問のルール"
echo ""
echo "- **選択肢形式を優先**: 自由記述より選択肢（2〜4個）を提示"
echo "- **推奨を明示**: 推奨オプションを最初に配置し「(Recommended)」を付ける"
echo "- **1質問1観点**: 複数の観点を1つの質問に詰め込まない"
echo "- **段階的に深掘り**: 回答に応じて追加質問で詳細化"
echo "- **クリアになるまで繰り返す**: 曖昧さが残る場合は追加質問"
echo ""
echo "### Step 4: 要件登録"
echo ""
echo "対話で明確化した要件を登録："
echo ""
echo '```'
echo "mcp__guardrails__procedure_workflow(action='requirements', goal='全体のゴール', requirements=["
echo "  {"
echo "    actor: '誰が',"
echo "    want: '何をしたい',"
echo "    because: 'なぜ（課題）',"
echo "    acceptance: '成功基準',"
echo "    constraints: ['制約1', '制約2']  // オプション"
echo "  }"
echo "])"
echo '```'
echo ""
echo "### Step 5: タスク計画"
echo ""
echo "要件登録後、以下でタスクを計画："
echo ""
echo '```'
echo "mcp__guardrails__procedure_workflow(action='plan')"
echo '```'
echo ""
echo "これにより、workflow-plannerサブエージェントがrunbooksを参照してタスクを提案します。"
echo ""
echo "**タスク粒度の原則: ステップを具体化してタスクにする**"
echo ""
echo "runbookの各ステップで「何を作るか」を具体化する。1成果物=1タスク。タスク数が多くなっても構わない。"
echo ""
echo "### Step 6: タスク登録（ユーザー承認後）"
echo ""
echo "タスク計画をユーザーに提示し、承認・修正後に登録："
echo ""
echo '```'
echo "mcp__guardrails__procedure_workflow(action='set', tasks=[...])"
echo '```'
echo ""
echo "**重要**: Goal登録 → 深掘りインタビュー → 要件登録 → タスク計画 → タスク登録の順序を守ること。"
echo ""
echo "### Step 7: タスク実行"
echo ""
echo "タスク登録後、進捗サマリーと次のタスクが自動表示される。"
echo ""
echo "1. 次のタスクを実行"
echo "2. 品質ゲート（後述）を通過"
echo "3. 完了マーク: \`procedure_workflow(action='done', index=N)\`"
echo "4. 次のタスクが自動表示される"
echo "5. 全タスク完了まで繰り返す"
echo ""
echo "---"
echo ""
echo "## 品質ゲート（実装時の循環）"
echo ""
echo "各タスクの実装後、以下の順序で品質を確認する:"
echo ""
echo "1. **静的解析**（最速フィードバック）"
echo "   mcp__guardrails__review_static_analysis → エラーがあれば修正"
echo ""
echo "2. **定性レビュー**"
echo "   guardrails-reviewerサブエージェント → 違反があればviolation-fixerで修正"
echo ""
echo "3. **循環**: 違反ゼロになるまで 1 → 2 を繰り返す"
echo ""
echo "**静的解析は定性レビューより先に実施すること。静的解析が最も早いフィードバック。**"
