/**
 * サービスID定義
 * InversifyのDIコンテナで使用する識別子
 */
export const serviceId = {
  // 環境変数
  LOG_LEVEL: "LOG_LEVEL",
  STAGE_NAME: "STAGE_NAME",
  USERS_TABLE_NAME: "USERS_TABLE_NAME",
  TODOS_TABLE_NAME: "TODOS_TABLE_NAME",
  PROJECTS_TABLE_NAME: "PROJECTS_TABLE_NAME",
  PROJECT_MEMBERS_TABLE_NAME: "PROJECT_MEMBERS_TABLE_NAME",
  ATTACHMENTS_TABLE_NAME: "ATTACHMENTS_TABLE_NAME",
  COGNITO_USER_POOL_ID: "COGNITO_USER_POOL_ID",
  COGNITO_CLIENT_ID: "COGNITO_CLIENT_ID",
  ALLOWED_ORIGINS: "ALLOWED_ORIGINS",
  ATTACHMENTS_BUCKET_NAME: "ATTACHMENTS_BUCKET_NAME",

  // ユーティリティ
  LOGGER: "LOGGER",
  FETCH_NOW: "FETCH_NOW",
  DDB_DOC: "DDB_DOC",
  COGNITO_CLIENT: "COGNITO_CLIENT",
  JWT_VERIFIER: "JWT_VERIFIER",
  AUTH_CLIENT: "AUTH_CLIENT",
  STORAGE_CLIENT: "STORAGE_CLIENT",
  S3_CLIENT: "S3_CLIENT",

  // リポジトリ
  USER_REPOSITORY: "USER_REPOSITORY",
  TODO_REPOSITORY: "TODO_REPOSITORY",
  PROJECT_REPOSITORY: "PROJECT_REPOSITORY",

  // Unit of Work
  DELETE_PROJECT_UOW_RUNNER: "DELETE_PROJECT_UOW_RUNNER",

  // ユースケース - User
  REGISTER_CURRENT_USER_USE_CASE: "REGISTER_CURRENT_USER_USE_CASE",
  LIST_USERS_USE_CASE: "LIST_USERS_USE_CASE",
  GET_USER_USE_CASE: "GET_USER_USE_CASE",
  GET_CURRENT_USER_USE_CASE: "GET_CURRENT_USER_USE_CASE",
  UPDATE_CURRENT_USER_USE_CASE: "UPDATE_CURRENT_USER_USE_CASE",
  DELETE_CURRENT_USER_USE_CASE: "DELETE_CURRENT_USER_USE_CASE",

  // ユースケース - Todo
  REGISTER_TODO_USE_CASE: "REGISTER_TODO_USE_CASE",
  LIST_TODOS_USE_CASE: "LIST_TODOS_USE_CASE",
  GET_TODO_USE_CASE: "GET_TODO_USE_CASE",
  UPDATE_TODO_USE_CASE: "UPDATE_TODO_USE_CASE",
  DELETE_TODO_USE_CASE: "DELETE_TODO_USE_CASE",

  // ユースケース - Attachment
  PREPARE_ATTACHMENT_UPLOAD_USE_CASE: "PREPARE_ATTACHMENT_UPLOAD_USE_CASE",
  UPDATE_ATTACHMENT_STATUS_USE_CASE: "UPDATE_ATTACHMENT_STATUS_USE_CASE",
  GET_ATTACHMENT_DOWNLOAD_URL_USE_CASE: "GET_ATTACHMENT_DOWNLOAD_URL_USE_CASE",
  DELETE_ATTACHMENT_USE_CASE: "DELETE_ATTACHMENT_USE_CASE",

  // ユースケース - Project
  LIST_PROJECTS_USE_CASE: "LIST_PROJECTS_USE_CASE",
  GET_PROJECT_USE_CASE: "GET_PROJECT_USE_CASE",
  CREATE_PROJECT_USE_CASE: "CREATE_PROJECT_USE_CASE",
  UPDATE_PROJECT_USE_CASE: "UPDATE_PROJECT_USE_CASE",
  DELETE_PROJECT_USE_CASE: "DELETE_PROJECT_USE_CASE",
  LIST_PROJECT_MEMBERS_USE_CASE: "LIST_PROJECT_MEMBERS_USE_CASE",
  INVITE_MEMBER_USE_CASE: "INVITE_MEMBER_USE_CASE",
  REMOVE_MEMBER_USE_CASE: "REMOVE_MEMBER_USE_CASE",
  LEAVE_PROJECT_USE_CASE: "LEAVE_PROJECT_USE_CASE",

  // ユースケース - User (検索)
  SEARCH_USERS_USE_CASE: "SEARCH_USERS_USE_CASE",
} as const;
