// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/signup/confirm": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/new": {
    params: {};
  };
  "/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/edit": {
    params: {
      "projectId": string;
    };
  };
  "/todos": {
    params: {};
  };
  "/todos/new": {
    params: {};
  };
  "/todos/:todoId": {
    params: {
      "todoId": string;
    };
  };
  "/todos/:todoId/edit": {
    params: {
      "todoId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/signup/confirm" | "/reset-password" | "/profile" | "/projects" | "/projects/new" | "/projects/:projectId" | "/projects/:projectId/edit" | "/todos" | "/todos/new" | "/todos/:todoId" | "/todos/:todoId/edit";
  };
  "features/auth/GuestLayout.tsx": {
    id: "features/auth/GuestLayout";
    page: "/login" | "/signup" | "/signup/confirm" | "/reset-password";
  };
  "routes/_guest+/login+/route.tsx": {
    id: "routes/_guest+/login+/route";
    page: "/login";
  };
  "routes/_guest+/signup+/route.tsx": {
    id: "routes/_guest+/signup+/route";
    page: "/signup";
  };
  "routes/_guest+/signup+/confirm+/route.tsx": {
    id: "routes/_guest+/signup+/confirm+/route";
    page: "/signup/confirm";
  };
  "routes/_guest+/reset-password+/route.tsx": {
    id: "routes/_guest+/reset-password+/route";
    page: "/reset-password";
  };
  "features/auth/AppLayout.tsx": {
    id: "features/auth/AppLayout";
    page: "/" | "/profile" | "/projects" | "/projects/new" | "/projects/:projectId" | "/projects/:projectId/edit" | "/todos" | "/todos/new" | "/todos/:todoId" | "/todos/:todoId/edit";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/profile/route.tsx": {
    id: "routes/profile/route";
    page: "/profile";
  };
  "routes/projects+/route.tsx": {
    id: "routes/projects+/route";
    page: "/projects";
  };
  "routes/projects+/new+/route.tsx": {
    id: "routes/projects+/new+/route";
    page: "/projects/new";
  };
  "routes/projects+/$projectId+/route.tsx": {
    id: "routes/projects+/$projectId+/route";
    page: "/projects/:projectId";
  };
  "routes/projects+/$projectId+/edit+/route.tsx": {
    id: "routes/projects+/$projectId+/edit+/route";
    page: "/projects/:projectId/edit";
  };
  "routes/todos+/route.tsx": {
    id: "routes/todos+/route";
    page: "/todos";
  };
  "routes/todos+/new+/route.tsx": {
    id: "routes/todos+/new+/route";
    page: "/todos/new";
  };
  "routes/todos+/$todoId+/route.tsx": {
    id: "routes/todos+/$todoId+/route";
    page: "/todos/:todoId";
  };
  "routes/todos+/$todoId+/edit+/route.tsx": {
    id: "routes/todos+/$todoId+/edit+/route";
    page: "/todos/:todoId/edit";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "features/auth/GuestLayout": typeof import("./src/app/features/auth/GuestLayout.tsx");
  "routes/_guest+/login+/route": typeof import("./src/app/routes/_guest+/login+/route.tsx");
  "routes/_guest+/signup+/route": typeof import("./src/app/routes/_guest+/signup+/route.tsx");
  "routes/_guest+/signup+/confirm+/route": typeof import("./src/app/routes/_guest+/signup+/confirm+/route.tsx");
  "routes/_guest+/reset-password+/route": typeof import("./src/app/routes/_guest+/reset-password+/route.tsx");
  "features/auth/AppLayout": typeof import("./src/app/features/auth/AppLayout.tsx");
  "routes/home/route": typeof import("./src/app/routes/home/route.tsx");
  "routes/profile/route": typeof import("./src/app/routes/profile/route.tsx");
  "routes/projects+/route": typeof import("./src/app/routes/projects+/route.tsx");
  "routes/projects+/new+/route": typeof import("./src/app/routes/projects+/new+/route.tsx");
  "routes/projects+/$projectId+/route": typeof import("./src/app/routes/projects+/$projectId+/route.tsx");
  "routes/projects+/$projectId+/edit+/route": typeof import("./src/app/routes/projects+/$projectId+/edit+/route.tsx");
  "routes/todos+/route": typeof import("./src/app/routes/todos+/route.tsx");
  "routes/todos+/new+/route": typeof import("./src/app/routes/todos+/new+/route.tsx");
  "routes/todos+/$todoId+/route": typeof import("./src/app/routes/todos+/$todoId+/route.tsx");
  "routes/todos+/$todoId+/edit+/route": typeof import("./src/app/routes/todos+/$todoId+/edit+/route.tsx");
};